# Automatically updated by the winget bot at 2021/Feb/22
Id: FileBot.FileBot
Publisher: Point Planck Limited
Author: rednoah
Name: FileBot
AppMoniker: filebot
Homepage: https://www.filebot.net/
Description: Tool for organizing and renaming movies, TV shows, anime or music.
Tags: FileBot, Renamer, Plex, Kodi, Emby, Checksum, CRC32, MD5, SHA256, Utility, License, Admin
License: Copyright © 2021 Point Planck Limited. All rights reserved.
Version: 4.9.3
InstallerType: msi
Installers:
- Arch: x64
  Url: https://get.filebot.net/filebot/FileBot_4.9.3/FileBot_4.9.3_x64.msi
  Sha256: 5D743F782CCF91DC06472E90E00B99A3AF39FF95F52F0E90822751E7B0E5DF8B
  Switches:
    Silent: /Quiet
    SilentWithProgress: /Passive
