# Automatically updated by the winget bot at 2021/Mar/01
Id: Microsoft.AzureStorageExplorer
Name: Azure Storage Explorer
AppMoniker: StorageExplorer
Version: 1.18.0
Publisher: Microsoft Corporation
Author: Microsoft
License: Microsoft
LicenseUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx
MinOSVersion: 10.0.0.0
Homepage: https://azure.microsoft.com/en-us/features/storage-explorer/
Description: Free tool to easily manage your Azure cloud storage resources anywhere, from Windows, macOS, or Linux.
Tags: "Azure, Storage, Storage Explorer, Azure Storage Explorer, Explorer"
InstallerType: exe
Installers:
- Arch: x64
  Url: https://go.microsoft.com/fwlink/?LinkId=708343&clcid=0x409
  Sha256: 30837828F272C60D2609E72ED47D709C526C440BD691B172E2DB6DE73023C251
  Language: en-US
  Switches:
    Silent: "/SILENT /NORESTART /ALLUSERS"
    SilentWithProgress: "/VERYSILENT /NORESTART /ALLUSERS"
