# Automatically updated by the winget bot at 2020/Dec/28
Id: TopalaSoftwareSolutions.SIW
Publisher: Topala Software Solutions
Name: System Information for Windows
AppMoniker: siw
MinOSVersion: 6.1.0.0
Version: 2021.02.20.0
Description: System Information for Windows - Everything you want to know about your computer
License: Commercial
LicenseUrl: https://www.gtopala.com/agreement/
Homepage: https://www.gtopala.com/
Installers:
- Arch: Neutral
  Url: https://siw64.com/download/siwtrial-setup.exe
  Sha256: E296FA639AFBA0B78817958F932FCD3E670BFABD20DCB4AF49DFDA43CC8C28E1
  InstallerType: Inno
  Switches:
    Silent: /VERYSILENT
    SilentWithProgress: /VERYSILENT
