# Automatically updated by the winget bot at 2021/Feb/13
Id: Amazon.AWSCLI
Publisher: AWS
Name: AWS Command Line Interface v1
Version: 1.19.7
License: Copyright 2012-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved. Licensed under the Apache License, Version 2.0
LicenseUrl: https://github.com/aws/aws-cli/blob/1.18.214/LICENSE.txt
Author: Amazon Web Services
AppMoniker: aws
Tags: cli, aws, amazon
Description: Universal Command Line Interface for Amazon Web Services
Homepage: https://aws.amazon.com/cli/
InstallerType: msi
Installers:
- Arch: x64
  Url: https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi
  Sha256: C260C406FCB0281B98DEDFAB724311EFD13712DF465FD16B3011ECBE7298A53E
  ProductCode: "{1C96DE4D-A969-4067-8E2C-0473F22800B7}"
  Switches:
    Silent: /quiet /norestart
    SilentWithProgress: /passive /norestart
