# Automatically updated by the winget bot at 2021/Feb/16
Id: ProtonTechnologies.ProtonMailBridge
Publisher: Proton Technologies
Name: ProtonMail Bridge
Version: 1.6.3
AppMoniker: protonmailbridge
Description: A bridge for paid ProtonMail users to encrypt and decrypt mail from a local mail client
Homepage: https://protonmail.com/bridge/
Tags: email, imap, smtp
License: Copyright (c) Proton Technologies AG
Switches:
  Silent: /qn
  SilentWithProgress: /qb
InstallerType: exe
Installers:
- Arch: x64
  Url: https://protonmail.com/download/Bridge-Installer.exe
  Sha256: ABB8351742C26719B0FC178797EEF1B07CD0E5D2AA1ED2FD624E202DB11008A2
