# Automatically updated by the winget bot at 2021/Feb/27
Id: GuinpinSoft.MakeMKV
Version: v1.16.0
Name: MakeMKV
Publisher: GuinpinSoft
License: Copyright © 2008-2020 GuinpinSoft inc
LicenseUrl: https://www.makemkv.com/aboutmkv/
AppMoniker: makemkv
Description: MakeMKV is your one-click solution to convert video that you own into free and patents-unencumbered format that can be played everywhere.
Homepage: https://www.makemkv.com/
Installers:
- Arch: Neutral
  Url: https://www.makemkv.com/download/Setup_MakeMKV_v1.16.0.exe
  Sha256: F9BC8D0049B9FE2D67587990409790CB5B72CDB3E4018EB354F2D63D7AD7E9A4
  InstallerType: nullsoft
